[window]
dynamic_padding = true
opacity = 1.0

[font]
normal      = {family="JetBrainsMono Nerd Font", style="Regular"}
bold        = {family="JetBrainsMono Nerd Font", style="Bold"}
italic      = {family="JetBrainsMono Nerd Font", style="Italic"}
bold_italic = {family="JetBrainsMono Nerd Font", style="Bold Italic"}

offset.x = 0
offset.y = 0

size = 11

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
foreground = "#FFFFFF"
background = "#111111"

[colors.normal]
black = "#444444"
red = "#CC2233"
green = "#11CC22"
yellow = "#CC9900"
blue = "#3020CC"
magenta = "#CC2288"
cyan = "#11AADD"
white = "#C0C0D3"

[colors.bright]
black = "#222222"
red = "#ff2222"
green = "#22ff44"
yellow = "#ffff00"
blue = "#3f30ff"
magenta = "#ff4499"
cyan = "#22ccff"
white = "#FFFFFF"
